### PR TITLE
[WIP] add support of JSON instead of XML

### PR DESCRIPTION
**Pull request by gluckzhang**
In this PR, we will use `xStream`+`JettisonMappedXmlDriver` to serialize/deserialize objects in json format (#26).

TODOs

- [x] In `pankti-instrument`, serialize objects to json string
- [x] In `pankti-generate`, generate test cases based on json strings
- [x] In `pankti-generate`, deserialize objects from json strings
- [ ] In `pankti-generate`, pretty-print short json strings

ref: https://www.baeldung.com/xstream-json-processing

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @Deee92 , please take a look at the todos above. Do I understand it correctly?

**Comment by Deee92** [comment]
@gluckzhang this seems correct. Let me know if you need any clarifications along the way.

**Comment by monperrus** [comment]
here is an idea which simplifies greatly the setup: to obtain the JSON profiles, we simply do `deserialize(XML).serialize(json)`

By doing so:

- we don't change anything in the object collection pipeline and test generation configuration from XML (and we minimize the risks of breaking something), we only change the text of the generated tests.
- we add a step `convert XML file to JSON file`
- we add an validation step `run the tests based on JSON` (some will fail if the JSON converter is buggy)
- then Pankti naturally supports both XML and JSON and possible Xstream converters, it's a nice configuration paper to claim in the paper, and also matters for the end user.

WDYT?

**Comment by Deee92** [comment]
@monperrus, that sounds like a neat idea.
[This paper](https://ieeexplore.ieee.org/abstract/document/6215346?casa_token=HD2IK19Nq4cAAAAA:3IIKhFCplHteNTwG7J9Ta_cZboVSe_pX1vUxedWFtDp1nfMpNeqdIF9wOajuQ6O69rqIn1RVPA) mentions both XML and JSON implementations with XStream.

**Comment by Deee92** [comment]
From the paper:
> The worst one [in terms of execution time] is serialization in JSON using XStream. It takes about 10 milliseconds to serialize an order objects with options. It is very slower than other serialization techniques. The worst top three are XStream in JSON, JsonLib and XStream in XML. To clarify the details, Fig. 10 shows fourteen techniques without the three. If serialization in JSON is required, Jackson is the best choice from the viewpoint of execution time.

**Comment by gluckzhang** [comment]
Hi @monperrus ,

I also prefer your idea, which makes it more configurable and simpler. In this way the json converter should be a standalone library, is it correct? I am worried that if we don't set up the json driver for xstream but convert the XML to JSON by ourselves, there might be some issues when the json is converted back to XML for deserialization using xstream. (The XML strings should meet xstream's conventions.)

**Comment by gluckzhang** [comment]
@Deee92 , thanks for the useful paper! Now we have more choices and off-the-shelf analysis on them :)
Regarding performance (the execution time to serialize/deserialize objects), we do need a low-overhead library for Glowroot's plugin as it is in a production environment. For deserialization I think it is fine, even the lowest one (JsonLib) only takes 22ms in their example.

**Comment by monperrus** [comment]
> I also prefer your idea, which makes it more configurable and simpler

cool!


>  In this way the json converter should be a standalone library, is it correct?

Correct, which is used offline to re-serialize to JSON and deserialize 
in the tests.

**Comment by monperrus** [comment]
Plus this technique enables the tests to use any JSON or XML library of the project under consideration if it already uses one, without very little changes in Pankti itself (only the test pretty-printer).

**Comment by gluckzhang** [comment]
> Plus this technique enables the tests to use any JSON or XML library of the project under consideration if it already uses one, without very little changes in Pankti itself (only the test pretty-printer).

Hi @monperrus , yes, I see what you mean. That's cool. Pankti could also inspect the project's pom first, to see if there is any serialization library is already used. Then it uses the same one to deserialize the xml/json :)

Regarding the step `convert XML file to JSON file`, I think pankti should use `xstream` to deserialize the object first, then we use a standalone library to re-serialize the object to xml/json for test generation. Is this correct?

**Comment by monperrus** [comment]
> I think pankti should use xstream to deserialize the object first, then we use a standalone library to re-serialize the object to xml/json for test generation. Is this correct?

yes, Panktu always serialize in XML with XStream, and do the analysis of 
those files; Only the very last step is impacted.

**Comment by gluckzhang** [comment]
Hi @Deee92 , @monperrus ,

As we are going to deserialize XML to objects first (if the output format is json), is there a way to load the corresponding classes in the target project? Does Spoon provide such features?

In `pankti-generate` if I directly run something like `xstream.fromXML(xmlString)`, I will get a `CannotResolveClassException` from xStream. Because the class in the xmlString comes from the target project, which is not loaded when we run `pankti-generate`.

**Comment by Deee92** [comment]
@gluckzhang, @monperrus, that's true. That's how it finds which methods in which classes to generate tests for. @gluckzhang, do you think we can have a quick meeting today to figure this out?

**Comment by gluckzhang** [comment]
@Deee92 a quick meeting sounds great. Thanks!

**Comment by gluckzhang** [comment]
Hi @monperrus, after discussing with @Deee92 , we find that in order to deserialize XML string using xStream (sth like `xStream.fromXML(xmlStr)`), the classes (maybe including the dependencies) in the target project need to be loaded. This is not the case in the current implementation because Spoon only needs the source code.

So I am implementing the following feature:

- Providing an `enum` option serializer for `pankti-generate` so that users can specify which serializer they want to use. Currently, two options are on the plan: `xstream`, and `gson` (future work: analyze the pom file in the target project to see if there exists a serializer already)
- Providing an optional option `classfiles` for `pankti-generate` which is needed when the serializer is not xstream. I will write a classloader for xstream to load these classes so that the deserialization is successful. 
- Providing an interface called `ISerializer` that abstracts methods like `serializeObjectToString`, `deserializeObjectFromString`, `generateCodeSnippets` etc.

Since it is quite different than the current PR, what about closing this one? I will propose another PR with the new idea. WDYT? My WIP branch is here: https://github.com/castor-software/pankti/tree/configurable-deserializer

**Comment by gluckzhang** [comment]
Concrete todo after our meeting:
A PR that use xStream+JsonDriver to generate test files with object strings in json. This could be done using the method [here](https://github.com/castor-software/pankti/blob/configurable-deserializer/pankti-generate/src/main/java/se/kth/castor/pankti/generate/generators/TestGeneratorUtil.java#L113). In this way we do not need to specify the path to classfiles in the target project.

**Comment by gluckzhang** [comment]
I am closing this PR for now. Though I really like to implement a configurable serializer for `pankti-generate`, let's take a small step for now: #33 :)

**Pull request closed without merging**
