### PR TITLE
feat: support generating tests with json

### PR DESCRIPTION
**Pull request by gluckzhang**
As discussed in #26 and #27, this PR provides a new option `--format` for `pankti-generate` which specifies the object string's format in the generated tests. By default, the value is `xml` and `pankti-generate` uses XML object strings in tests. Otherwise when `--format json` is given, the object strings are written in json in the generated tests.

Future work: pretty-print short json strings.

### CODE REVIEW

**Comment by monperrus** [comment]
nice! what about having a unit test case to check that the feature works well?

**Comment by gluckzhang** [comment]
> nice! what about having a unit test case to check that the feature works well?

Good idea. I am working on this now :)

**Comment by monperrus** [comment]
cool to test our testing tools :-)

**Comment by gluckzhang** [comment]
Hi @monperrus @Deee92 , I have added two unit tests for method `transformXML2JSON`. This PR is ready to be merged :)

**Pull request merged**
